export enum ProcessLogType {
    GetFromSource,
    ObjSourceToIdeas,
    ProcessAfterSource,
    TotalSource,
    TotalProcess,
    gettingDescriptiveInfo,
    TotalProcessDB,
    GetAdditionalInfo,
    ProcessDBBooking,
    ProcessDBPassenger,
    ProcessDBBookingSource,
    ProcessDBBookingSegments,
    ProcessDBBookingFares,
    ProcessDBBookingTickets,
    ProcessDBBookingSeats,
    ProcessDBStatusBooking,
    ProcessDBAdditional
}